"""Option 2 visual engine: original editorial storyboard graphics.

This module deliberately does NOT retrieve news photographs. It converts the
verified script/evidence into a scene-by-scene visual language using an LLM
only for editorial layout selection and deterministic Pillow renderers for the
actual pixels. No new factual claims are generated by the visual engine.
"""
from __future__ import annotations

import json
import os
import re
from typing import Any

import requests
from PIL import Image, ImageDraw, ImageFont

PIPELINE_ID = "option2_storyboard_v1"
ORIGINAL_SOURCE_CREDIT = "Original factory editorial graphic"
ALLOWED_MODES = {
    "LEAD", "ENTITY", "FACT", "STAT", "TIMELINE", "COMPARE",
    "PROCESS", "RANKING", "SCORECARD", "TACTICAL", "LOCATION", "QUOTE",
}

BG_TOP = (247, 244, 236)
BG_BOTTOM = (231, 238, 235)
INK = (17, 32, 34)
MUTED = (77, 97, 98)
ACCENT = (15, 104, 99)
ACCENT_2 = (226, 111, 57)
PANEL = (255, 252, 246, 238)
PANEL_LINE = (204, 214, 210)

_NUMBER_RE = re.compile(
    r"(?<!\w)(?:[$€£₹]\s*)?\d{1,3}(?:[,.]\d{3})*(?:\.\d+)?\s*"
    r"(?:%|million|billion|thousand|m|bn|k|runs?|goals?|matches?|years?|"
    r"days?|months?|points?|wins?|losses?|minutes?)?",
    re.IGNORECASE,
)
_YEAR_RE = re.compile(r"(?<!\d)(?:19\d{2}|20\d{2}|21\d{2})(?!\d)")
_SCORE_RE = re.compile(r"(?<!\d)(\d{1,3})\s*[-–:]\s*(\d{1,3})(?!\d)")
_QUOTE_RE = re.compile(r"[\"“”']([^\"“”']{8,180})[\"“”']")


def _safe_font(path: str | None, size: int):
    candidates = [
        path or "",
        os.path.join(os.path.dirname(__file__), "NotoSansDevanagari-Bold.ttf"),
        os.path.join(os.path.dirname(__file__), "NotoSansTelugu-Bold.ttf"),
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf",
        r"C:\Windows\Fonts\segoeuib.ttf",
        r"C:\Windows\Fonts\arialbd.ttf",
    ]
    for candidate in candidates:
        try:
            if candidate and os.path.isfile(candidate):
                return ImageFont.truetype(candidate, int(size))
        except Exception:
            pass
    return ImageFont.load_default()


def _clean(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


def _sentences(text: str) -> list[str]:
    cleaned = _clean(text)
    if not cleaned:
        return []
    return [part.strip() for part in re.split(r"(?<=[.!?])\s+", cleaned) if part.strip()]


def _short(text: str, limit: int = 96) -> str:
    text = _clean(text)
    if len(text) <= limit:
        return text
    clipped = text[:limit + 1].rsplit(" ", 1)[0].strip()
    return (clipped or text[:limit]).rstrip(".,;:") + "…"


def _metrics(text: str) -> list[str]:
    found = []
    for match in _NUMBER_RE.finditer(str(text or "")):
        value = _clean(match.group(0))
        if value and value not in found:
            found.append(value)
    return found[:4]


def _years(text: str) -> list[str]:
    found = []
    for year in _YEAR_RE.findall(str(text or "")):
        if year not in found:
            found.append(year)
    return found[:5]


def _score(text: str) -> str:
    match = _SCORE_RE.search(str(text or ""))
    return f"{match.group(1)} – {match.group(2)}" if match else ""


def _quote(text: str) -> str:
    match = _QUOTE_RE.search(str(text or ""))
    return _short(match.group(1), 150) if match else ""


def _wrap(draw: ImageDraw.ImageDraw, text: str, font, max_width: int) -> list[str]:
    words = _clean(text).split()
    if not words:
        return []
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        try:
            width = draw.textbbox((0, 0), candidate, font=font)[2]
        except Exception:
            width = len(candidate) * max(8, getattr(font, "size", 16))
        if current and width > max_width:
            lines.append(current)
            current = word
        else:
            current = candidate
    if current:
        lines.append(current)
    return lines


def _draw_wrapped(draw, xy, text, font, fill, max_width, line_gap=10, max_lines=None):
    lines = _wrap(draw, text, font, max_width)
    if max_lines and len(lines) > max_lines:
        lines = lines[:max_lines]
        lines[-1] = _short(lines[-1], max(16, len(lines[-1])))
    x, y = xy
    line_height = int(getattr(font, "size", 30) * 1.12)
    for line in lines:
        draw.text((x, y), line, font=font, fill=fill)
        y += line_height + line_gap
    return y


def _canvas(font_path: str | None, kicker: str, mode: str):
    width, height = 1080, 1920
    image = Image.new("RGBA", (width, height), BG_TOP + (255,))
    draw = ImageDraw.Draw(image)
    for y in range(height):
        ratio = y / max(1, height - 1)
        color = tuple(int(BG_TOP[i] * (1 - ratio) + BG_BOTTOM[i] * ratio) for i in range(3)) + (255,)
        draw.line((0, y, width, y), fill=color)

    # restrained deterministic texture; the visual language stays original.
    for idx in range(18):
        x = 40 + ((idx * 193) % 980)
        y = 160 + ((idx * 317) % 1500)
        radius = 8 + (idx % 4) * 5
        draw.ellipse((x - radius, y - radius, x + radius, y + radius), fill=(255, 255, 255, 38))

    draw.rounded_rectangle(
        (58, 58, 1022, 1862), radius=42,
        fill=(255, 255, 255, 85), outline=PANEL_LINE + (170,), width=2,
    )
    draw.text((90, 96), _short(kicker.upper(), 42), font=_safe_font(font_path, 28), fill=ACCENT)
    pill_font = _safe_font(font_path, 22)
    mode_text = mode.replace("_", " ")
    box = draw.textbbox((0, 0), mode_text, font=pill_font)
    pill_w = box[2] - box[0] + 42
    draw.rounded_rectangle(
        (1022 - pill_w - 38, 88, 1022 - 38, 144),
        radius=28, fill=ACCENT + (24,), outline=ACCENT + (80,), width=2,
    )
    draw.text((1022 - pill_w - 17, 102), mode_text, font=pill_font, fill=ACCENT)
    return image, draw


def _panel(draw, box, radius=30):
    draw.rounded_rectangle(box, radius=radius, fill=PANEL, outline=PANEL_LINE, width=2)


def _accent_bar(draw, x, y, width, height=12):
    draw.rounded_rectangle((x, y, x + width, y + height), radius=height // 2, fill=ACCENT)


def _deterministic_mode(scene: dict[str, Any], index: int) -> str:
    text = _clean(scene.get("voiceover"))
    intent = _clean(scene.get("visual_intent"))
    category = _clean(scene.get("sport_or_topic_category")).lower()
    lower = f"{text} {intent}".lower()
    if index == 0:
        return "LEAD"
    if _quote(text):
        return "QUOTE"
    if _score(text) and any(token in lower for token in ("score", "won", "beat", "defeat", "match", "final")):
        return "SCORECARD"
    if any(token in lower for token in (
        "timeline", "since", "before", "after", "in 2019", "in 2020",
        "in 2021", "in 2022", "in 2023", "in 2024", "in 2025", "in 2026",
    )) and len(_years(text)) >= 2:
        return "TIMELINE"
    if any(token in lower for token in ("compared", "versus", " vs ", "against", "more than", "less than")):
        return "COMPARE"
    if any(token in lower for token in ("step", "how it works", "process", "works like", "first", "then", "finally")):
        return "PROCESS"
    if any(token in lower for token in ("top ", "ranked", "ranking", "number one", "second", "third", "most", "least")):
        return "RANKING"
    if any(token in lower for token in (
        "formation", "press", "pressing", "batting", "bowling", "tactic",
        "tactical", "lineup", "line-up", "xi", "shape",
    )) and any(token in category for token in ("sport", "cricket", "football", "soccer")):
        return "TACTICAL"
    if _metrics(text):
        return "STAT"
    if any(token in lower for token in ("city", "country", "state", "located", "based in", "from ")):
        return "LOCATION"
    if scene.get("primary_entity"):
        return "ENTITY"
    return "FACT"


def _planner_prompt(script_data: dict[str, Any], scenes: list[dict[str, Any]]) -> str:
    scene_lines = []
    for index, scene in enumerate(scenes, 1):
        scene_lines.append(
            f"SCENE {index}\n"
            f"VOICEOVER: {_clean(scene.get('voiceover'))}\n"
            f"ENTITY: {_clean(scene.get('primary_entity'))}\n"
            f"VISUAL INTENT: {_clean(scene.get('visual_intent'))}\n"
            f"CATEGORY: {_clean(scene.get('sport_or_topic_category'))}\n"
        )
    evidence = _clean(script_data.get("research_evidence_text"))[:9000]
    return (
        "You are an editorial motion-graphics director. Choose only the best visual form for each scene. "
        "Do NOT invent facts, people, numbers, quotes, dates, locations or logos. The render engine will only "
        "display information already present in the supplied scene voiceover/evidence. Return JSON only.\n\n"
        "ALLOWED MODES: LEAD, ENTITY, FACT, STAT, TIMELINE, COMPARE, PROCESS, RANKING, SCORECARD, TACTICAL, LOCATION, QUOTE.\n"
        "Rules: scene 1 should normally be LEAD; use SCORECARD only when an explicit score exists; use QUOTE only when quoted text exists; "
        "use TIMELINE only when at least two dates/years appear; use TACTICAL only when the scene is genuinely sports tactical; "
        "otherwise prefer FACT, ENTITY or STAT. Keep the plan minimal and varied.\n\n"
        f"TITLE: {_clean(script_data.get('title') or (script_data.get('titles') or [''])[0])}\n"
        f"EVIDENCE: {evidence}\n\n" +
        "\n".join(scene_lines) +
        "\n\nOUTPUT: {\"scenes\":[{\"mode\":\"LEAD|ENTITY|FACT|STAT|TIMELINE|COMPARE|PROCESS|RANKING|SCORECARD|TACTICAL|LOCATION|QUOTE\"}]}"
    )


def _post_json(url: str, headers: dict[str, str], payload: dict[str, Any], timeout: int = 30):
    try:
        response = requests.post(url, headers=headers, json=payload, timeout=timeout)
        if response.status_code != 200:
            return None
        data = response.json()
        return data if isinstance(data, dict) else None
    except Exception:
        return None


def _llm_plan(script_data: dict[str, Any], scenes: list[dict[str, Any]]) -> tuple[list[str], str]:
    prompt = _planner_prompt(script_data, scenes)
    groq_key = os.getenv("GROQ_API_KEY", "").strip()
    if groq_key:
        result = _post_json(
            "https://api.groq.com/openai/v1/chat/completions",
            {"Authorization": f"Bearer {groq_key}", "Content-Type": "application/json"},
            {
                "model": "openai/gpt-oss-120b",
                "messages": [
                    {"role": "system", "content": "Return only valid JSON matching the requested schema."},
                    {"role": "user", "content": prompt},
                ],
                "response_format": {"type": "json_object"},
                "temperature": 0.15,
            },
        )
        try:
            raw = result["choices"][0]["message"]["content"] if result else ""
            parsed = json.loads(raw)
            modes = [
                str(item.get("mode") or "").upper()
                for item in parsed.get("scenes", [])
                if isinstance(item, dict)
            ]
            if modes:
                return modes, "groq"
        except Exception:
            pass

    gemini_key = os.getenv("GEMINI_API_KEY", "").strip()
    if gemini_key:
        result = _post_json(
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key="
            + gemini_key,
            {"Content-Type": "application/json"},
            {
                "contents": [{"role": "user", "parts": [{"text": prompt}]}],
                "generationConfig": {"temperature": 0.15, "responseMimeType": "application/json"},
            },
        )
        try:
            raw = result["candidates"][0]["content"]["parts"][0]["text"] if result else ""
            parsed = json.loads(raw)
            modes = [
                str(item.get("mode") or "").upper()
                for item in parsed.get("scenes", [])
                if isinstance(item, dict)
            ]
            if modes:
                return modes, "gemini"
        except Exception:
            pass

    return [], "deterministic"


def _normalise_modes(llm_modes: list[str], scenes: list[dict[str, Any]]) -> list[str]:
    fallback = [_deterministic_mode(scene, index) for index, scene in enumerate(scenes)]
    result: list[str] = []
    for index, scene in enumerate(scenes):
        candidate = str(llm_modes[index] if index < len(llm_modes) else "").upper().strip()
        if candidate not in ALLOWED_MODES:
            candidate = fallback[index]
        if candidate == "SCORECARD" and not _score(scene.get("voiceover", "")):
            candidate = fallback[index]
        if candidate == "QUOTE" and not _quote(scene.get("voiceover", "")):
            candidate = fallback[index]
        if candidate == "TIMELINE" and len(_years(scene.get("voiceover", ""))) < 2:
            candidate = fallback[index]
        result.append(candidate)
    if result:
        result[0] = "LEAD"
    return result


def _render_lead(scene, font_path):
    entity = _clean(scene.get("primary_entity")) or "The story"
    sentence = _short(scene.get("voiceover"), 150)
    image, draw = _canvas(font_path, "CURRENT STORY", "LEAD")
    _panel(draw, (92, 300, 988, 1560))
    draw.ellipse((118, 410, 388, 680), fill=ACCENT + (28,), outline=ACCENT, width=5)
    initials = "".join(word[0] for word in entity.split()[:2]).upper() or "•"
    draw.text((185, 485), initials, font=_safe_font(font_path, 88), fill=ACCENT)
    draw.text((430, 380), "WHAT CHANGED", font=_safe_font(font_path, 30), fill=ACCENT)
    _draw_wrapped(draw, (430, 450), _short(entity, 34), _safe_font(font_path, 60), INK, 470, line_gap=8, max_lines=3)
    _accent_bar(draw, 132, 790, 190)
    _draw_wrapped(draw, (132, 870), sentence, _safe_font(font_path, 50), INK, 800, line_gap=12, max_lines=6)
    draw.text(
        (132, 1430),
        "Original editorial visual · copy remains grounded in the verified script",
        font=_safe_font(font_path, 23),
        fill=MUTED,
    )
    return image


def _render_entity(scene, font_path):
    entity = _clean(scene.get("primary_entity")) or "Key subject"
    intent = _short(scene.get("visual_intent") or "Why this subject matters in the story", 120)
    body = _short(scene.get("voiceover"), 150)
    image, draw = _canvas(font_path, "STORY SUBJECT", "ENTITY")
    _panel(draw, (92, 300, 988, 1550))
    draw.ellipse((136, 380, 356, 600), fill=ACCENT + (20,), outline=ACCENT + (80,), width=4)
    initials = "".join(word[0] for word in entity.split()[:2]).upper() or "•"
    draw.text((206, 440), initials, font=_safe_font(font_path, 74), fill=ACCENT)
    draw.text((400, 410), "SUBJECT", font=_safe_font(font_path, 26), fill=MUTED)
    _draw_wrapped(draw, (400, 458), _short(entity, 40), _safe_font(font_path, 60), INK, 510, line_gap=10, max_lines=3)
    _draw_wrapped(draw, (138, 700), intent, _safe_font(font_path, 32), ACCENT, 800, line_gap=8, max_lines=3)
    _draw_wrapped(draw, (138, 870), body, _safe_font(font_path, 43), INK, 800, line_gap=12, max_lines=7)
    return image


def _render_stat(scene, font_path):
    metrics = _metrics(scene.get("voiceover"))
    body = _short(scene.get("voiceover"), 120)
    image, draw = _canvas(font_path, "NUMBERS THAT MATTER", "STAT")
    _panel(draw, (92, 300, 988, 1610))
    title = _short(scene.get("primary_entity") or "The key numbers", 46)
    draw.text((132, 370), title, font=_safe_font(font_path, 48), fill=INK)
    if metrics:
        cols = 2 if len(metrics) > 1 else 1
        card_w = 380 if cols == 2 else 760
        for index, value in enumerate(metrics[:4]):
            col = index % cols
            row = index // cols
            x = 132 + col * 400
            y = 520 + row * 320
            _panel(draw, (x, y, x + card_w, y + 240))
            draw.text((x + 30, y + 30), value, font=_safe_font(font_path, 62), fill=ACCENT)
            draw.text((x + 30, y + 118), "from the narration", font=_safe_font(font_path, 24), fill=MUTED)
    _draw_wrapped(draw, (132, 1420), body, _safe_font(font_path, 34), INK, 800, line_gap=8, max_lines=4)
    return image


def _render_timeline(scene, font_path):
    years = _years(scene.get("voiceover"))
    sentences = _sentences(scene.get("voiceover"))
    image, draw = _canvas(font_path, "HOW WE GOT HERE", "TIMELINE")
    _panel(draw, (92, 300, 988, 1600))
    draw.line((180, 570, 180, 1410), fill=ACCENT, width=10)
    for index, year in enumerate(years[:5]):
        y = 620 + index * 170
        draw.ellipse((145, y - 20, 215, y + 50), fill=ACCENT)
        draw.text((260, y - 28), year, font=_safe_font(font_path, 44), fill=ACCENT)
        snippet = _short(sentences[index] if index < len(sentences) else scene.get("voiceover"), 72)
        _draw_wrapped(draw, (260, y + 38), snippet, _safe_font(font_path, 28), INK, 620, line_gap=5, max_lines=2)
    return image


def _render_compare(scene, font_path):
    entity = _clean(scene.get("primary_entity")) or "Subject"
    image, draw = _canvas(font_path, "CONTEXT", "COMPARE")
    _panel(draw, (92, 340, 988, 1550))
    _panel(draw, (132, 540, 500, 920))
    _panel(draw, (580, 540, 948, 920))
    draw.text((168, 605), _short(entity, 28), font=_safe_font(font_path, 44), fill=INK)
    draw.text((620, 605), "THE COMPARISON", font=_safe_font(font_path, 40), fill=INK)
    draw.ellipse((474, 675, 606, 807), fill=ACCENT + (25,), outline=ACCENT, width=4)
    draw.text((505, 708), "VS", font=_safe_font(font_path, 34), fill=ACCENT)
    _draw_wrapped(draw, (140, 1030), _short(scene.get("voiceover"), 180), _safe_font(font_path, 40), INK, 800, line_gap=10, max_lines=8)
    return image


def _render_process(scene, font_path):
    sentences = _sentences(scene.get("voiceover"))[:3]
    image, draw = _canvas(font_path, "BREAK IT DOWN", "PROCESS")
    for index in range(3):
        y = 340 + index * 440
        _panel(draw, (92, y, 988, y + 340))
        draw.ellipse((130, y + 55, 220, y + 145), fill=ACCENT + (30,), outline=ACCENT, width=3)
        draw.text((161, y + 76), str(index + 1), font=_safe_font(font_path, 34), fill=ACCENT)
        snippet = _short(sentences[index] if index < len(sentences) else scene.get("voiceover"), 120)
        _draw_wrapped(draw, (258, y + 64), snippet, _safe_font(font_path, 34), INK, 650, line_gap=8, max_lines=5)
    return image


def _render_ranking(scene, font_path):
    image, draw = _canvas(font_path, "ORDER MATTERS", "RANKING")
    _panel(draw, (92, 320, 988, 1580))
    metrics = _metrics(scene.get("voiceover"))[:4]
    sentence_list = _sentences(scene.get("voiceover"))[:4]
    for index in range(4):
        y = 430 + index * 260
        draw.text((140, y), f"0{index + 1}", font=_safe_font(font_path, 42), fill=ACCENT)
        snippet = _short(sentence_list[index] if index < len(sentence_list) else scene.get("voiceover"), 90)
        _draw_wrapped(draw, (260, y + 3), snippet, _safe_font(font_path, 31), INK, 560, line_gap=4, max_lines=3)
        if index < len(metrics):
            draw.text((830, y), metrics[index], font=_safe_font(font_path, 32), fill=ACCENT_2)
    return image


def _render_scorecard(scene, font_path):
    image, draw = _canvas(font_path, "MATCH RESULT", "SCORECARD")
    _panel(draw, (92, 430, 988, 1380))
    score = _score(scene.get("voiceover")) or "—"
    entity = _short(scene.get("primary_entity") or "Result", 42)
    draw.text((142, 520), entity, font=_safe_font(font_path, 44), fill=INK)
    draw.text((142, 700), score, font=_safe_font(font_path, 156), fill=ACCENT)
    _draw_wrapped(draw, (142, 940), _short(scene.get("voiceover"), 160), _safe_font(font_path, 38), INK, 790, line_gap=8, max_lines=7)
    return image


def _render_tactical(scene, font_path):
    image, draw = _canvas(font_path, "TACTICAL CONTEXT", "TACTICAL")
    _panel(draw, (92, 300, 988, 1600))
    field = (160, 470, 920, 1260)
    draw.rounded_rectangle(field, radius=24, fill=(236, 243, 238, 255), outline=ACCENT, width=4)
    draw.line((field[0] + 40, (field[1] + field[3]) // 2, field[2] - 40, (field[1] + field[3]) // 2), fill=PANEL_LINE, width=3)
    draw.ellipse((405, 760, 675, 1030), outline=PANEL_LINE, width=3)
    for idx, (x, y) in enumerate(((300, 590), (470, 650), (640, 590), (260, 1060), (530, 1120), (720, 1060))):
        draw.ellipse((x - 24, y - 24, x + 24, y + 24), fill=ACCENT if idx < 3 else ACCENT_2)
    draw.line((350, 720, 710, 900), fill=ACCENT_2, width=10)
    draw.polygon([(710, 900), (680, 884), (689, 918)], fill=ACCENT_2)
    _draw_wrapped(draw, (140, 1360), _short(scene.get("voiceover"), 170), _safe_font(font_path, 34), INK, 800, line_gap=8, max_lines=5)
    return image


def _render_location(scene, font_path):
    image, draw = _canvas(font_path, "WHERE IT MATTERS", "LOCATION")
    _panel(draw, (92, 320, 988, 1570))
    draw.ellipse((150, 470, 930, 1250), outline=ACCENT, width=6)
    draw.arc((300, 470, 780, 1250), start=90, end=270, fill=PANEL_LINE, width=3)
    draw.arc((300, 470, 780, 1250), start=270, end=90, fill=PANEL_LINE, width=3)
    draw.line((180, 860, 900, 860), fill=PANEL_LINE, width=3)
    draw.line((240, 650, 840, 650), fill=PANEL_LINE, width=3)
    entity = _short(scene.get("primary_entity") or "Location", 38)
    draw.text((150, 1320), entity, font=_safe_font(font_path, 52), fill=INK)
    _draw_wrapped(draw, (150, 1400), _short(scene.get("voiceover"), 120), _safe_font(font_path, 30), MUTED, 780, line_gap=6, max_lines=4)
    return image


def _render_quote(scene, font_path):
    quote = _quote(scene.get("voiceover")) or _short(scene.get("voiceover"), 140)
    image, draw = _canvas(font_path, "ON THE RECORD", "QUOTE")
    _panel(draw, (92, 360, 988, 1530))
    draw.text((140, 470), "“", font=_safe_font(font_path, 160), fill=ACCENT)
    _draw_wrapped(draw, (150, 650), quote, _safe_font(font_path, 52), INK, 780, line_gap=14, max_lines=8)
    draw.text((150, 1310), "Quoted wording is only shown when it is present in the verified scene.", font=_safe_font(font_path, 24), fill=MUTED)
    return image


def _render_fact(scene, font_path):
    image, draw = _canvas(font_path, "THE FACT", "FACT")
    _panel(draw, (92, 350, 988, 1510))
    entity = _short(scene.get("primary_entity") or "Key fact", 44)
    draw.text((140, 430), entity, font=_safe_font(font_path, 48), fill=ACCENT)
    _draw_wrapped(draw, (140, 560), _short(scene.get("voiceover"), 250), _safe_font(font_path, 48), INK, 800, line_gap=12, max_lines=10)
    return image


_RENDERERS = {
    "LEAD": _render_lead,
    "ENTITY": _render_entity,
    "FACT": _render_fact,
    "STAT": _render_stat,
    "TIMELINE": _render_timeline,
    "COMPARE": _render_compare,
    "PROCESS": _render_process,
    "RANKING": _render_ranking,
    "SCORECARD": _render_scorecard,
    "TACTICAL": _render_tactical,
    "LOCATION": _render_location,
    "QUOTE": _render_quote,
}


def _render_scene(scene: dict[str, Any], mode: str, font_path: str | None) -> Image.Image:
    renderer = _RENDERERS.get(mode, _render_fact)
    return renderer(scene, font_path).convert("RGB")


async def build_storyboard_visuals(
    bot,
    script_data: dict[str, Any],
    language_cfg: dict[str, Any],
    format_mode: str = "regular",
):
    """Build Option 2 visual packages without image scraping."""
    scenes = script_data.get("script") or []
    if not isinstance(scenes, list) or not scenes:
        raise RuntimeError("Option 2 visual engine received no script scenes.")

    scene_dicts = [dict(scene) if isinstance(scene, dict) else {"voiceover": str(scene)} for scene in scenes]
    llm_modes, planner = _llm_plan(script_data, scene_dicts)
    modes = _normalise_modes(llm_modes, scene_dicts)
    font_path = language_cfg.get("font") if isinstance(language_cfg, dict) else None

    os.makedirs(bot.ASSETS_DIR, exist_ok=True)
    packages: list[list[dict[str, Any]]] = []
    provenance = list(script_data.get("visual_provenance") or []) if isinstance(script_data.get("visual_provenance"), list) else []
    print(f"\n🧠 Option 2 storyboard planner: provider={planner}; scenes={len(scene_dicts)}", flush=True)

    for index, (scene, mode) in enumerate(zip(scene_dicts, modes), 1):
        path = os.path.join(bot.ASSETS_DIR, f"scene_{index}_img.jpg")
        image = _render_scene(scene, mode, font_path)
        image.save(path, "JPEG", quality=95, optimize=True)

        entity = _clean(scene.get("primary_entity"))
        scene["visual_pipeline"] = PIPELINE_ID
        scene["visual_storyboard_mode"] = mode
        scene["visual_verified"] = True
        scene["visual_qc_blocked"] = False
        scene["visual_qc_block_reason"] = ""
        scene["visual_rescue_reason"] = ""
        scene["visual_fallback_reason"] = ""
        scene["visual_query_used"] = ""
        scene["visual_provider_query_used"] = ""
        scene["visual_original_path"] = path
        scene["visual_source"] = "editorial_graphic"
        scene["visual_type"] = f"STORYBOARD_{mode}"
        scene["visual_genre"] = "EDITORIAL_GRAPHIC"
        scene["asset_provenance"] = {
            "pipeline": PIPELINE_ID,
            "asset_type": "original_editorial_graphic",
            "planner": planner,
            "external_photo_used": False,
            "factual_copy_source": "verified_scene_voiceover",
            "source_credit": ORIGINAL_SOURCE_CREDIT,
        }

        packages.append([{
            "image": path,
            "text": "" if str(format_mode) == "top5" else scene.get("voiceover", ""),
            "narration_text": scene.get("voiceover", ""),
            "ai_generated": False,
            "source_type": "editorial_graphic",
            "visual_type": f"STORYBOARD_{mode}",
            "visual_genre": "EDITORIAL_GRAPHIC",
            "visual_verified": True,
            "visual_qc_blocked": False,
            "visual_qc_block_reason": "",
            "visual_rejection_counts": {},
            "visual_rescue_reason": "",
            "visual_fallback_reason": "",
            "visual_query_used": "",
            "manual_visual_query": "",
            "manual_visual_query_score": 0,
            "source_credit": ORIGINAL_SOURCE_CREDIT,
            "source_image_url": "",
            "asset_provenance": dict(scene["asset_provenance"]),
            "visual_asset_bank": [],
            "visual_original_path": path,
            "visual_manual_pool_mode": False,
            "visual_manual_pool_size": 0,
            "visual_manual_pool_query_stats": [],
            "visual_manual_pool": [],
            "visual_pipeline": PIPELINE_ID,
            "visual_storyboard_mode": mode,
        }])

        provenance.append({
            "type": "original_editorial_graphic",
            "pipeline": PIPELINE_ID,
            "scene_index": index,
            "mode": mode,
            "planner": planner,
            "source": "verified_scene_voiceover",
            "credit": ORIGINAL_SOURCE_CREDIT,
            "external_photo_used": False,
        })
        print(f"   [Option 2] Scene {index} -> {mode} | entity='{entity}'", flush=True)

    script_data["script"] = scene_dicts
    script_data["visual_pipeline"] = PIPELINE_ID
    script_data["visual_storyboard_plan"] = [
        {"scene_index": index, "mode": mode, "planner": planner}
        for index, mode in enumerate(modes, 1)
    ]
    script_data["visual_provenance"] = provenance
    script_data["visual_manual_queries"] = []
    script_data["visual_manual_pool"] = []
    script_data["visual_manual_pool_size"] = 0
    script_data["visual_manual_pool_query_stats"] = []
    script_data["visual_manual_pool_rejection_counts"] = {}
    script_data["ai_image_ratio"] = 0.0
    return packages
